### ISSUE TITLE
Sent messages should NOT count as *new*

### ISSUE THREAD

**Issue by grant-olson** [grant-olson/BitMessageForum#52]
They don't for the ajax feed, but they also shouldn't show _new_ on the Messages or Sent entries on the menu.

**Comment by medoix** [comment]
I can stop this appearing in the UX but not sure if something should be changed on the back end to prevent sent being seen as _new_ ?

**Comment by grant-olson** [comment]
Yeah it's a code issue.  Should have assigned it to myself.

**Comment by medoix** [comment]
It also needs to be removed from the UX so ill keep an eye on this issue.

**Comment by grant-olson** [comment]
I removed 'new' from the sent menu entry.  From a quick look at the code, it doesn't seem like it should actually show new on the main menu bar if there are only new sent messages.  But I swear I saw this, so I'm going to keep the issue open until I can confirm.
