### ISSUE TITLE
Message with subject containing / gives 404 as the url thinks its a different page.

### ISSUE THREAD

**Issue by medoix** [grant-olson/BitMessageForum#63]
/ in subject cause the url to become invalid and returns a 404 page not found.

**Comment by grant-olson** [comment]
I can't reproduce this.  Can you give me the exact subject or send me a message with the subject that breaks for you?

**Comment by medoix** [comment]
I noticed you responded to my message with the / in it but i cannot open it haha, what did you say?

**Comment by grant-olson** [comment]
Heh.  It's working for me.  And when I view the raw source the link is indeed percent-escaped.  We don't include a slash.

**Comment by medoix** [comment]
Fixed it in my Virtualhost config for Apache. Needed to add 'AllowEncodedSlashes NoDecode'
